name: cloc

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  pull-requests: write

jobs:
  cloc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Install cloc
        run: sudo apt install cloc

      - name: Run cloc
        id: run-cloc
        run: |
          cloc --git --diff --by-file main HEAD | tail -n +5 > cloc_output.txt

      - name: cloc results
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const fs = require('fs');
            const txt = fs.readFileSync('cloc_output.txt', 'utf8');
            const output = `\`\`\`\n${txt}\n\`\`\``;
            const comments = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const botComment = comments.data.find(comment => comment.user.login === 'github-actions[bot]');
            if (botComment) {
              await github.rest.issues.updateComment({
                comment_id: botComment.id,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              });
            } else {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              });
            }

      - name: Cleanup
        run: rm cloc_output.txt
