name: cloc

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  pull-requests: write

jobs:
  cloc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install cloc
        run: sudo apt install cloc

      - name: Run cloc
        id: run-cloc
        run: cloc ./ --by-file

      - name: cloc results
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            console.log(steps.run-cloc.outputs);
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ steps.run-cloc.outputs }}'
            })

# jobs:
#   build:
#     name: Post welcome comment
#     runs-on: ubuntu-latest
#     steps:
#       - run: gh pr comment $PR_URL --body "Welcome to the repository!"
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           PR_URL: ${{ github.event.pull_request.html_url }}
