name: cloc

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  pull-requests: write

jobs:
  cloc:
    runs-on: ubuntu-latest
    outputs:
      cloc: ${{ steps.run-cloc.outputs.cloc }}
    steps:
      - uses: actions/checkout@v3
      - name: Install cloc
        run: sudo apt install cloc

      - name: Run cloc
        id: run-cloc
        run: |
          OUTPUT=$(cloc ./ --by-file)
          echo "::set-output name=cloc::${OUTPUT}"

      - name: cloc results
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const output = `${{ steps.run-cloc.outputs.cloc }}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
