name: cloc

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

permissions:
  pull-requests: write

jobs:
  cloc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install cloc
        run: |
          sudo apt install cloc

      - name: Run cloc
        id: run-cloc
        run: |
          git fetch origin main
          cloc --ignore-whitespace --git --diff --by-file --exclude-dir=node_modules,dotnet,.github --not-match-f=^.+\.spec\.ts$ origin/main HEAD | tail -n +5 > cloc_output.txt
          echo "action_state=yellow" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.action_state }}"
      - name: Cleanup
        run: rm cloc_output.txt
